---

version: '3'
services:
  obsidian:
    build: .
    image: truongmanhsang/obsidian-remote
    container_name: obsidian
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data/vaults:/vaults
      - ./data/config:/config 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - CUSTOM_USER=user
      - PASSWORD=pass
